# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     maruku
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Hom
description: Hom's Blog for Science and Technique 
keywords: Hom Technique IT
url: http://platinhom.github.io
feed: /atom.xml
favicon: /images/shortcut.jpg

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: Zhixiong Zhao
    email: zhaozxcpu(at)hotmail.com
    imageLink: /images/header.jpg
    simpleIntro: Interested in Computer-Aided Drug Design, IT, Chemoinformatics
    detailIntro:
      <p>I got my B.S. from China Pharmaceutical University in Pharmacy and Ph.D. from Shanghai Institute of Organic Chemistry, CAS. I did the organic mass spectrometric research before my change to computational study. </p>
      <p>Computation related sciences need to remember lots of informations. Here I just put some notes on my blog here. Hope it help! </p>
      <p>Love science, Love your own life.</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/234020806/
  - class: icon-facebook
    url: http://facebook.com/
  - class: icon-github-alt
    url: http://github.com/platinhom
  - class: icon-twitter
    url: http://twitter.com/
  - class: icon-google-plus
    url: https://plus.google.com/114637369386965423989/about

#Links
customLinks:
  - item:
    - text: 技术小黑屋
      url: http://droidyue.com/
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
    message: Friends    
  - item:
    - text: Java Code Geeks
      url: http://www.javacodegeeks.com/
    - text: Web Developer
      url: http://www.fromdev.com/
    - text: BeginnersBook
      url: http://beginnersbook.com/
    - text: Mkyong
      url: http://www.mkyong.com/
    - text: Java By Nataraj
      url: http://javabynataraj.blogspot.in/
    message: About Java

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: UA-58146229-1

#baidu tongji
baiduTongji:
  config: false
  id: c12b560f0372d5995701449b9eac606c

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: platinhom

#baidu share config
baiduShare:
  config: false
  
